name: support_app
description: "AI-Powered Machine Tool Support App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  injectable: ^2.0.0
  dio: ^5.0.0
  shared_preferences: ^2.0.15
  go_router: ^16.2.1
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  injectable_generator: ^2.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

  assets:
    - assets/fonts/
    - assets/images/