"""empty message

Revision ID: 06496dc16160
Revises: f9d100ea23bb
Create Date: 2025-08-31 19:15:15.152053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06496dc16160'
down_revision: Union[str, Sequence[str], None] = 'f9d100ea23bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('machinemodel',
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('owned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('serial_number'),
    sa.UniqueConstraint('owned')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machinemodel')
    op.drop_table('employee')
    # ### end Alembic commands ###
