"""empty message

Revision ID: 23cafbc2af0c
Revises: 06496dc16160
Create Date: 2025-08-31 19:31:38.784009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cafbc2af0c'
down_revision: Union[str, Sequence[str], None] = '06496dc16160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'employee', ['employee_id'])
    op.drop_constraint(op.f('machinemodel_owned_key'), 'machinemodel', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('machinemodel_owned_key'), 'machinemodel', ['owned'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'employee', type_='unique')
    # ### end Alembic commands ###
