"""empty message

Revision ID: 6758bca691bf
Revises: c03289dd3f1b
Create Date: 2025-09-07 06:04:04.360032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6758bca691bf'
down_revision: Union[str, Sequence[str], None] = 'c03289dd3f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anomaly_reports', 'status',
               existing_type=postgresql.ENUM('SUBMITTED', 'UNDER_REVIEW', 'KB_INCORPORATED', 'CLOSED', name='anomalystatus'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('anomaly_reports', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='anomalypriority'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'role',
               existing_type=postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               nullable=False)
    op.drop_index('idx_chat_messages_session_id', table_name='chat_messages')
    op.drop_index('idx_chat_sessions_machine_id', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_user_id', table_name='chat_sessions')
    op.add_column('error_codes', sa.Column('related_machine_model', sa.JSON(), nullable=True))
    op.alter_column('error_codes', 'manufacturer_origin',
               existing_type=postgresql.ENUM('MACHINE', 'CHILLER', 'LASER_SOURCE', 'DRIVE', 'CONTROLLER', 'SOFTWARE', 'OTHER', name='manufacturerorigin'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('error_codes', 'severity',
               existing_type=postgresql.ENUM('MINOR', 'WARNING', 'CRITICAL', name='errorseverity'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('knowledge_base_contents', 'content_type',
               existing_type=postgresql.ENUM('DOCUMENT', 'FAQ', 'TROUBLESHOOTING_GUIDE', 'VIDEO', 'TUTORIAL', 'ERROR_GUIDE', name='contenttype'),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('machinemodel', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('machines', sa.Column('brand', sa.String(length=100), nullable=True))
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'ESCALATED', name='ticketstatus'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('CUSTOMER', 'ADMIN', 'TECHNICIAN', 'SALES_AGENT', name='userrole'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CUSTOMER', 'ADMIN', 'TECHNICIAN', 'SALES_AGENT', name='userrole'),
               existing_nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=sa.String(),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'),
               existing_nullable=False)
    op.alter_column('tickets', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'ESCALATED', name='ticketstatus'),
               existing_nullable=False)
    op.drop_column('machines', 'brand')
    op.drop_column('machinemodel', 'brand')
    op.alter_column('knowledge_base_contents', 'content_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('DOCUMENT', 'FAQ', 'TROUBLESHOOTING_GUIDE', 'VIDEO', 'TUTORIAL', 'ERROR_GUIDE', name='contenttype'),
               existing_nullable=False)
    op.alter_column('error_codes', 'severity',
               existing_type=sa.String(),
               type_=postgresql.ENUM('MINOR', 'WARNING', 'CRITICAL', name='errorseverity'),
               existing_nullable=True)
    op.alter_column('error_codes', 'manufacturer_origin',
               existing_type=sa.String(),
               type_=postgresql.ENUM('MACHINE', 'CHILLER', 'LASER_SOURCE', 'DRIVE', 'CONTROLLER', 'SOFTWARE', 'OTHER', name='manufacturerorigin'),
               existing_nullable=True)
    op.drop_column('error_codes', 'related_machine_model')
    op.create_index('idx_chat_sessions_user_id', 'chat_sessions', ['user_id'])
    op.create_index('idx_chat_sessions_machine_id', 'chat_sessions', ['machine_id'])
    op.create_index('idx_chat_messages_session_id', 'chat_messages', ['session_id'])
    op.alter_column('chat_messages', 'content',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'),
               existing_nullable=False)
    op.alter_column('anomaly_reports', 'priority',
               existing_type=sa.String(),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='anomalypriority'),
               existing_nullable=False)
    op.alter_column('anomaly_reports', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('SUBMITTED', 'UNDER_REVIEW', 'KB_INCORPORATED', 'CLOSED', name='anomalystatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
