"""empty message

Revision ID: 80fc4573371a
Revises: 0d8db021545a
Create Date: 2025-09-03 11:05:16.633266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80fc4573371a'
down_revision: Union[str, Sequence[str], None] = '0d8db021545a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column('machinemodel', sa.Column('model', sa.String(), nullable=True))
    op.add_column('machinemodel', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machinemodel', 'type')
    op.drop_column('machinemodel', 'model')

    # ### end Alembic commands ###
