"""add_chat_tables

Revision ID: c03289dd3f1b
Revises: 80fc4573371a
Create Date: 2025-09-04 10:19:00.697914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03289dd3f1b'
down_revision: Union[str, Sequence[str], None] = '80fc4573371a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create document table if it doesn't exist
    try:
        op.create_table('document',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(), nullable=False),
            sa.Column('content', sa.String(), nullable=False),
            sa.Column('document_type', sa.String(), nullable=False),
            sa.Column('machine_type', sa.String(), nullable=True),
            sa.Column('file_path', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    except Exception:
        # Table might already exist
        pass
    
    # Create indexes for document table (if they don't exist)
    try:
        op.create_index(op.f('ix_document_document_type'), 'document', ['document_type'], unique=False)
    except Exception:
        pass
    
    try:
        op.create_index(op.f('ix_document_machine_type'), 'document', ['machine_type'], unique=False)
    except Exception:
        pass
    
    try:
        op.create_index(op.f('ix_document_title'), 'document', ['title'], unique=False)
    except Exception:
        pass
    
    # Note: chat_sessions and chat_messages tables were already created manually
    # The title column and content column already exist
    # Indexes were also created manually
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop document table indexes
    try:
        op.drop_index(op.f('ix_document_title'), table_name='document')
    except Exception:
        pass
    
    try:
        op.drop_index(op.f('ix_document_machine_type'), table_name='document')
    except Exception:
        pass
    
    try:
        op.drop_index(op.f('ix_document_document_type'), table_name='document')
    except Exception:
        pass
    
    # Drop document table
    try:
        op.drop_table('document')
    except Exception:
        pass
    # ### end Alembic commands ###
